### ISSUE TITLE
a calculating variable q_vadv code is wrong.

### ISSUE THREAD

**Issue by yumatsuoka** [DaikiShimada/masalachai#10]
I think the below code from 90 to 91 at trainers/vat.py on master branch is wrong. That's because we have to use "distance_calculaters[hoge]['activation']()" on VirtualAdversarialTrainer class for changeable distance calculation instead of softmax().

`q_vadv = chainer.functions.softmax(self.optimizer.target.predictor(x0 + self.r_vadv))`

I wanna fix it if it is wrong, you also think so. Then, I hope you make a 'vat' branch and I'll commit the fixed one at same branch on my forked repository.

**Comment by DaikiShimada** [comment]
Thanks, @yumatsuoka .
I've created `vat` branch.
Please send me your Pull Request.

**Comment by yumatsuoka** [comment]
Alright. I'll send it.

**Comment by DaikiShimada** [comment]
@yumatsuoka 
I've merged your PR. Please check it.
